remote_theme: "pmarsceill/just-the-docs"
title: Netgíró
heading_anchors: true
logo: "/images/brand-logo.svg"
footer_content: "© 2019 Netgíró hf. - Kt: 6812122050 | Borgartúni 27, 105 Reykjavík | Sími: 4 300 330 | netgiro@netgiro.is"
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"
