remote_theme: "pmarsceill/just-the-docs"
title: Netgíró
heading_anchors: true
logo: "https://user-images.githubusercontent.com/47334837/66752194-29c5ac80-ee91-11e9-8c01-30e919383b77.png"
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"
