title: Netgíró
theme: just-the-docs

logo: "/images/brand-logo.svg"
favicon_ico: "/images/favicon.ico"

heading_anchors: true
footer_content: "© 2022 Netgíró Greiðslumiðlun. - Kt: 5101222830 | Katrínartún 2, 105 Reykjavík | Sími: 4 300 330 | netgiro@netgiro.is"

permalink: /:title/
aux_links:
  "Just the Docs on GitHub":
    - "//github.com/pmarsceill/just-the-docs"
